version: '3'
services:
  app:
    image: ikurek/hometrack-remote
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postpass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hometrack
    restart: always